routes/web.php
<?php

use App\Http\Controllers\StudentController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Route::resource('students', StudentController::class)
                    ->names('students');

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    use HasFactory;

    protected $fillable = [
        "name",
        "address",
        "image",
        "phone",
        "email",
        "bio",
        "status"
    ];
}

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Models\Student;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //tous les étudiants
        $etudiants = Student::all();

        return view('students.index',compact('etudiants'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('students.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required',
            'address' => '',
            'image' => 'required|image|mimes:png,jpg,jpeg,gif,svg|max:2000',
            'phone' => 'required',
            'email' => 'required',
            'bio' => '',
            'statut' => ''
        ]);

        //dd($validated);
        $path = $request->file('image')->store('public/images');
        $validated['image'] = $path;
        Student::create($validated);

        return back()
        ->with('success', "l'étudiant enregistré avec succès !");
    }

    /**
     * Display the specified resource.
     */
    public function show(Student $student)
    {
        return view('students.show', compact('student'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Student $student)
    {
        return view('students.edit', compact('student'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Student $student)
    {
        
        $validated = $request->validate([
            'name' => 'required',
            'address' => '',
            'image' => '',
            'phone' => 'required',
            'email' => 'required',
            'bio' => '',
            'statut' => ''
        ]);

        //dd($request->file('image'));

        if($request->file('image') !=null){
            Storage::delete($student->image);
            $path = $request->file('image')->store('public/images');
            $validated['image'] = $path;  
        }else{
            $validated['image'] = $student->image;
        }

        $student->update($validated);

        return redirect()
            ->route('students.index')
            ->with('success', 'Etudiant Modifié avec succès !');
        

    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Student $student)
    {
        Storage::delete($student->image);
        $student->delete();
        return back()->with('success', 'Etudiant supprimé !');
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@yield('title')</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        @include("layouts.header")
    </header>
    <main>
        <div class="container">
            @yield("content")
        </div>
    </main>
    <footer>
        @include("layouts.footer")
    </footer>
</body>
</html>

resources/views/layouts/header.blade.php
<nav class="navbar navbar-expand-md navbar-dark bg-primary">
    <a class="navbar-brand" href="#">
        Gestion des étudiants
    </a>
    <button class="navbar-toggler d-lg-none" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavId" aria-controls="collapsibleNavId"
        aria-expanded="false" aria-label="Toggle navigation"></button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav me-auto mt-2 mt-lg-0">
            <li class="nav-item">
                <a class="nav-link active" href="/" aria-current="page">Accueil <span class="visually-hidden">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="dropdownId" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Etudiants</a>
                <div class="dropdown-menu" aria-labelledby="dropdownId">
                    <a class="dropdown-item" href="{{ route("students.create") }}">Nouvel étudiant</a>
                    <a class="dropdown-item" href="{{  route('students.index') }}">Liste des étudiants</a>
                </div>
            </li>
        </ul>
        <form class="d-flex my-2 my-lg-0">
            <input class="form-control me-sm-2" type="text" placeholder="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

resources/views/students/create.blade.php
@extends('layouts.app')

@section("title", "Enregistrement d'un étudiant")

@section("content")
    <div class="row">
        <h3>Enregistrement d'un étudiant</h3>
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        @if (Session::has('success'))
            <div class="alert alert-success">
                {{ Session::get('success') }}
            </div>
        @endif
        <form enctype="multipart/form-data"
            action="{{ route('students.store') }}" method="post">
            @csrf
            @include('students.form')
        </form>
    </div>
@endsection

resources/views/students/edit.blade.php
@extends("layouts.app")

@section("title", "Modification d'un étudiant")

@section("content")
    <div class="row">
        <h3>Formulaire de modification d'un étudiant</h3>
        <form 
        enctype="multipart/form-data" 
        action="{{ route('students.update', $student->id) }}" 
        method="post">
        @csrf
        @method("PUT")
        @include('students.form')
    </form>
    </div>
@endsection

resources/views/students/form.blade.php
<div class="form-floating mb-3">
    <input
      value="@isset($student->name){{ $student->name }}@endisset"
      type="text"
      class="form-control" name="name" id="name" 
      placeholder="Votre nom complet :">
    <label for="name">Votre nom complet :</label>
  </div>
  <div class="form-floating mb-3">
      <input 
      value="@isset($student->address){{ $student->address }}@endisset"
      type="text" class="form-control" 
          name="address" id="address"
          placeholder="Votre adresse : ">
      <label for="address">Votre adresse : </label>
  </div>
  <div class="mb-3">
      <label for="image" class="form-label">
          Votre Image
      </label>
      <input 
          class="form-control"
          type="file" name="image" id="image">
  </div>
  <div class="form-floating mb-3">
      <input 
          value="@isset($student->phone){{ $student->phone }}@endisset"
          class="form-control"
          placeholder="Votre numéro de téléphone"
          type="tel" name="phone" id="phone">
      <label for="phone">
          Votre numéro de téléphone : 
      </label>
  </div>
  <div class="form-floating mb-3">
    <input
      value="@isset($student->email){{ $student->email }}@endisset"
      type="email"
      class="form-control" name="email" id="email" 
      placeholder="Votre adresse email : ">
    <label for="email">
      Votre adresse email : 
    </label>
  </div>
  <div class="form-floating mb-3">
      <textarea 
      class="form-control"
      placeholder="Votre biographie : "
      name="bio" id="bio">@isset($student->bio){{ $student->bio }}@endisset</textarea>
      <label for="bio">Votre biographie : </label>
  </div>
  <div class="form-check mb-3">
      <input 
          class="form-check-input"
          value="1" @isset($student->status) checked @endisset 
          type="checkbox" name="status" id="status">
      <label for="status" class="form-check-label">
          Statut de l'étudiant
      </label>
  </div>
  <div class="d-grid gap-2 mb-3">
      <button type="submit" class="btn btn-primary">
          Enregistrer cet étudiant
      </button>
  </div>

resources/views/students/index.blade.php
@extends("layouts.app")

@section("title", "La liste des étudiants")

@section("content")
    <div class="row">
        <h3>La liste des étudiants</h3>
        @if (Session::has('success'))
            <div class="alert alert-success">
                {{ Session::get('success') }}
            </div>
        @endif
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th>Nom complet</th>
                    <th>Adresse</th>
                    <th>Email</th>
                    <th>Téléphone</th>
                    <th>Ations</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($etudiants as $etudiant)
                    <tr>
                        <td>{{ $etudiant->name }}</td>
                        <td>{{ $etudiant->address }}</td>
                        <td>{{ $etudiant->email }}</td>
                        <td>{{ $etudiant->phone }}</td>
                        <td style="display: flex">
                            <a class="btn btn-sm btn-primary" style="margin-right: 5px"
                                href="{{ route("students.show", $etudiant->id) }}">
                                Détail
                            </a>
                            <a class="btn btn-warning btn-sm" style="margin-right: 5px" 
                                href="{{ route("students.edit", $etudiant->id) }}">
                                Modifier
                            </a>
                            <form 
                                action="{{ route('students.destroy', $etudiant->id) }}" 
                                method="post">
                                @csrf
                                @method('DELETE')
                                <button onclick="return confirm('Êtes-vous sûr ?')"
                                    type="submit" class="btn btn-sm btn-danger">
                                    Supprimer
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/students/show.blade.php
@extends("layouts.app")

@section("title", $student->name)

@section("content")
    <div class="row col-md-12 mt-5">
        <div class="col-md-4">
            <div class="text-center">
                <img width="200"
src="{{ asset('storage/'.str_replace('public/', '', $student->image)) }}" 
                class="rounded">
            </div>
        </div>
        <div class="col-md-8">
            <h3>Informations personnelles de l'étudiants</h3>
            <table class="table">
                
                <tbody>
                    <tr>
                        <td><b>Nom complet : </b> {{ $student->name }}</td>
                    </tr>
                    <tr>
                        <td><b>Adresse : </b>{{ $student->address }}</td>
                    </tr>
                    <tr>
                        <td><b>Email : </b>{{ $student->email }}</td>
                    </tr>
                    <tr>
                        <td><b>Téléphone : </b>{{ $student->phone }}</td>
                    </tr>
                    <tr>
                        <td><b>Biographie : </b>{{ $student->bio }}</td>
                    </tr>
                    <tr>
                        <td>
                            <b>Statut : </b>
                            @if($student->status == true)
                                <span class="badge text-bg-success">
                                    Actif
                                </span>
                                @else
                                <span class="badge text-bg-danger">
                                    désactivé
                                </span>
                            @endif
                        </td>
                    </tr>
                    <td>
                        <a class="btn btn-primary" href="{{ route('students.index') }}">
                            Retour à la liste
                        </a>
                    </td>
                </tbody>
            </table>
        </div>
    </div>
@endsection